package jvcdp.authapi.model;

import java.io.Serializable;
import java.util.Date;
/*import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;*/

public class UserInfo implements Serializable{
	/**
	 * 
	 */
	private static final long serialVersionUID = 144979817017745599L;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userinfo.id
     *
     * @mbg.generated Tue Sep 12 11:39:12 SGT 2017
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userinfo.name
     *
     * @mbg.generated Tue Sep 12 11:39:12 SGT 2017
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userinfo.username
     *
     * @mbg.generated Tue Sep 12 11:39:12 SGT 2017
     */
    private String username;

    public UserInfo() {
		super();
	}

	public UserInfo(Long id, String name, String username, String email, String passwordhash, String salt,
			Date createdate, Date lastlogin, Date lastupdate, String projectid) {
		super();
		this.id = id;
		this.name = name;
		this.username = username;
		this.email = email;
		this.passwordhash = passwordhash;
		this.salt = salt;
		this.createdate = createdate;
		this.lastlogin = lastlogin;
		this.lastupdate = lastupdate;
		this.projectid = projectid;
	}

	/**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userinfo.email
     *
     * @mbg.generated Tue Sep 12 11:39:12 SGT 2017
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userinfo.passwordhash
     *
     * @mbg.generated Tue Sep 12 11:39:12 SGT 2017
     */
    private String passwordhash;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userinfo.salt
     *
     * @mbg.generated Tue Sep 12 11:39:12 SGT 2017
     */
    private String salt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userinfo.createdate
     *
     * @mbg.generated Tue Sep 12 11:39:12 SGT 2017
     */
    private Date createdate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userinfo.lastlogin
     *
     * @mbg.generated Tue Sep 12 11:39:12 SGT 2017
     */
    private Date lastlogin;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userinfo.lastupdate
     *
     * @mbg.generated Tue Sep 12 11:39:12 SGT 2017
     */
    private Date lastupdate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userinfo.projectid
     *
     * @mbg.generated Tue Sep 12 11:39:12 SGT 2017
     */
    private String projectid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userinfo.id
     *
     * @return the value of userinfo.id
     *
     * @mbg.generated Tue Sep 12 11:39:12 SGT 2017
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userinfo.id
     *
     * @param id the value for userinfo.id
     *
     * @mbg.generated Tue Sep 12 11:39:12 SGT 2017
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userinfo.name
     *
     * @return the value of userinfo.name
     *
     * @mbg.generated Tue Sep 12 11:39:12 SGT 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userinfo.name
     *
     * @param name the value for userinfo.name
     *
     * @mbg.generated Tue Sep 12 11:39:12 SGT 2017
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userinfo.username
     *
     * @return the value of userinfo.username
     *
     * @mbg.generated Tue Sep 12 11:39:12 SGT 2017
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userinfo.username
     *
     * @param username the value for userinfo.username
     *
     * @mbg.generated Tue Sep 12 11:39:12 SGT 2017
     */
    public void setUsername(String username) {
        this.username = username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userinfo.email
     *
     * @return the value of userinfo.email
     *
     * @mbg.generated Tue Sep 12 11:39:12 SGT 2017
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userinfo.email
     *
     * @param email the value for userinfo.email
     *
     * @mbg.generated Tue Sep 12 11:39:12 SGT 2017
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userinfo.passwordhash
     *
     * @return the value of userinfo.passwordhash
     *
     * @mbg.generated Tue Sep 12 11:39:12 SGT 2017
     */
    public String getPasswordhash() {
        return passwordhash;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userinfo.passwordhash
     *
     * @param passwordhash the value for userinfo.passwordhash
     *
     * @mbg.generated Tue Sep 12 11:39:12 SGT 2017
     */
    public void setPasswordhash(String passwordhash) {
        this.passwordhash = passwordhash;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userinfo.salt
     *
     * @return the value of userinfo.salt
     *
     * @mbg.generated Tue Sep 12 11:39:12 SGT 2017
     */
    public String getSalt() {
        return salt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userinfo.salt
     *
     * @param salt the value for userinfo.salt
     *
     * @mbg.generated Tue Sep 12 11:39:12 SGT 2017
     */
    public void setSalt(String salt) {
        this.salt = salt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userinfo.createdate
     *
     * @return the value of userinfo.createdate
     *
     * @mbg.generated Tue Sep 12 11:39:12 SGT 2017
     */
    public Date getCreatedate() {
        return createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userinfo.createdate
     *
     * @param createdate the value for userinfo.createdate
     *
     * @mbg.generated Tue Sep 12 11:39:12 SGT 2017
     */
    public void setCreatedate(Date createdate) {
        this.createdate = createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userinfo.lastlogin
     *
     * @return the value of userinfo.lastlogin
     *
     * @mbg.generated Tue Sep 12 11:39:12 SGT 2017
     */
    public Date getLastlogin() {
        return lastlogin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userinfo.lastlogin
     *
     * @param lastlogin the value for userinfo.lastlogin
     *
     * @mbg.generated Tue Sep 12 11:39:12 SGT 2017
     */
    public void setLastlogin(Date lastlogin) {
        this.lastlogin = lastlogin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userinfo.lastupdate
     *
     * @return the value of userinfo.lastupdate
     *
     * @mbg.generated Tue Sep 12 11:39:12 SGT 2017
     */
    public Date getLastupdate() {
        return lastupdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userinfo.lastupdate
     *
     * @param lastupdate the value for userinfo.lastupdate
     *
     * @mbg.generated Tue Sep 12 11:39:12 SGT 2017
     */
    public void setLastupdate(Date lastupdate) {
        this.lastupdate = lastupdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userinfo.projectid
     *
     * @return the value of userinfo.projectid
     *
     * @mbg.generated Tue Sep 12 11:39:12 SGT 2017
     */
    public String getProjectid() {
        return projectid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userinfo.projectid
     *
     * @param projectid the value for userinfo.projectid
     *
     * @mbg.generated Tue Sep 12 11:39:12 SGT 2017
     */
    public void setProjectid(String projectid) {
        this.projectid = projectid;
    }
}
