            CREATE TABLE IF NOT EXISTS APPLICATION_USER(
            ID SERIAL NOT NULL PRIMARY KEY,
            NAME CHARACTER VARYING(255),
            USER_NAME CHARACTER VARYING(255),
            EMAIL CHARACTER VARYING(255),
            PASSWORD_HASH CHARACTER VARYING(255),
            SALT CHARACTER VARYING(255),
            LAST_LOGIN_TIME_STAMP TIMESTAMP,
            CREATE_TIME_STAMP TIMESTAMP,
            UPDATE_TIME_STAMP TIMESTAMP,
            API_ID CHARACTER VARYING(255));
